	 ORG 800H  
	 MVI A,0  
	 STA 0F26H  
	 STA 0F27H  
	 STA 0F28H  
	 STA 0F29H  
	 STA 0F2AH  
	 STA 0F1AH  
	 STA 0F19H  
	 STA 0F18H  
	 STA 0F17H  
	 STA 0F16H  
	 STA 0F0AH  
	 STA 0F09H  
	 STA 0F08H  
	 STA 0F07H  
	 STA 0F06H  
	 STA 0F05H  
	 LXI H,TEXT1  
	 RST 3  
	 CALL INCHAR  
	 CALL LOWER3  
	 CALL IFZERO  
	 JZ ZEROA  
	 CALL X10  
	 MOV C,A  
ZEROA 	 CALL INCHAR  
	 CALL CHECKFLAG  
	 JNZ A0NF  
	 CALL LOWER6  
A0NF 	 ADD C  
	 MOV B,A  
	 CALL IFZERO  
	 JZ ZEROB  
	 CALL X10  
	 MOV C,A  
ZEROB 	 CALL INCHAR  
	 CALL CHECKFLAG  
	 JNZ A1NF  
	 CALL LOWER6  
A1NF 	 ADD C  
	 CALL IFZERO  
	 JNZ ZEROC  
	 CALL NEWLINE  
	 LXI H,TEXTZERO  
	 RST 3  
	 HLT  
ZEROC 	 MOV C,A  
	 MVI A,0  
	 MVI L,0  
	 CALL NEWLINE  
	 LXI H,TEXT2  
	 RST 3  
	 CALL INCHAR  
	 CALL LOWER3  
	 STA 0F28H  
	 MOV D,A  
	 CALL INCHAR  
	 CALL CHECKFLAG  
	 JNZ B0NF  
	 CALL LOWER6  
B0NF 	 STA 0F29H  
	 ADD D  
	 MOV D,A  
	 CALL INCHAR  
	 CALL CHECKFLAG  
	 JNZ B1NF  
	 CALL LOWER6  
B1NF 	 STA 0F2AH  
	 ADD D  
	 CALL IFZERO  
	 JNZ CLRMULTIPLY  
	 CALL NEWLINE  
	 LXI H,TEXTZERO  
	 RST 3  
	 HLT  
CLRMULTIPLY 	 XRA A  
	 MVI B,0  
	 MVI D,0  
	 MVI E,0  
	 MVI H,0  
	 MVI L,0  
	 CALL CY2ZERO  
MULTIPLY 	 LDA 0F0AH  
CYFRA1 	 LXI H,0F1AH  
	 ADD M  
	 LXI H,0F2AH  
	 ADD M  
	 CALL COMP  
	 STA 0F1AH  
	 MVI A,0  
	 STA 0F09H  
	 JNC NOCARRY1  
	 MVI A,1  
	 STA 0F09H  
NOCARRY1 	 XRA A  
CYFRA2  
	 LDA 0F09H  
	 LXI H,0F19H  
	 ADD M  
	 LXI H,0F29H  
	 ADD M  
	 CALL COMP  
	 STA 0F19H  
	 MVI A,0  
	 STA 0F08H  
	 JNC NOCARRY2  
	 MVI A,1  
	 STA 0F08H  
NOCARRY2 	 XRA A  
CYFRA3  
	 LDA 0F08H  
	 LXI H,0F18H  
	 ADD M  
	 LXI H,0F28H  
	 ADD M  
	 CALL COMP  
	 STA 0F18H  
	 MVI A,0  
	 STA 0F07H  
	 JNC NOCARRY3  
	 MVI A,1  
	 STA 0F07H  
NOCARRY3 	 XRA A  
CYFRA4  
	 LDA 0F07H  
	 LXI H,0F17H  
	 ADD M  
	 LXI H,0F27H  
	 ADD M  
	 CALL COMP  
	 STA 0F17H  
	 MVI A,0  
	 STA 0F06H  
	 JNC NOCARRY4  
	 MVI A,1  
	 STA 0F06H  
NOCARRY4 	 XRA A  
CYFRA5  
	 LDA 0F06H  
	 LXI H,0F16H  
	 ADD M  
	 LXI H,0F26H  
	 ADD M  
	 CALL COMP  
	 STA 0F16H  
	 MVI A,0  
	 STA 0F05H  
	 JNC NOCARRY5  
	 MVI A,1  
	 STA 0F05H  
NOCARRY5 	 XRA A  
	 DCR C  
	 JNZ MULTIPLY  
	 CALL NEWLINE  
	 LXI H,TEXTRESULT  
	 RST 3  
	 LDA 0F16H  
	 ADI 030H  
	 RST 1  
	 LDA 0F17H  
	 ADI 030H  
	 RST 1  
	 LDA 0F18H  
	 ADI 030H  
	 RST 1  
	 LDA 0F19H  
	 ADI 030H  
	 RST 1  
	 LDA 0F1AH  
	 ADI 030H  
	 RST 1  
	 HLT  
COMP 	 CALL CY2ZERO  
	 CPI 0  
	 JZ COMPE  
	 MVI B,9  
COMP0 	 CMP B  
	 JZ COMPE  
	 DCR B  
	 JNZ COMP1  
	 CALL HEXA  
	 RET  
COMP1 	 JMP COMP0  
COMPE 	 CALL CY2ZERO  
	 RET  
HEXA 	 CALL HEXADEC  
	 DAA  
	 ANI 15  
	 ADD E  
	 MVI E,0  
	 STC  
	 RET  
HEXADEC 	 MOV D,A  
	 MVI B,013H  
HEXADEC0 	 MOV A,D  
	 CMP B  
	 JZ HEXFOUND  
	 DCR B  
	 MOV A,B  
	 CPI 0FH  
	 JNZ HEXADEC0  
	 XRA A  
	 MOV A,D  
	 RET  
HEXFOUND 	 SUI 6  
	 MVI E,6  
	 RET  
X10 	 MVI H,9  
X10A 	 ADD B  
	 DCR H  
	 JNZ X10A  
	 RET  
INCHAR 	 RST 2  
	 SBI 30H  
	 CALL ISNUMBER  
	 MOV B,A  
	 RET  
IFZERO 	 MVI H,0  
	 CMP H  
	 RET  
NEWLINE 	 MVI A,13D  
	 RST 1  
	 MVI A,10D  
	 RST 1  
	 RET  
ISNUMBER 	 CALL CY2ZERO  
	 CPI 0  
	 JZ TRUE0  
	 MVI B,9  
NUM90 	 CMP B  
	 JZ TRUE0  
	 DCR B  
	 JNZ NUM90  
	 CALL NEWLINE  
	 LXI H,TEXTNOTANUMBER  
	 RST 3  
	 HLT  
	 JNC CY2ZERO1234  
	 CMC  
CY2ZERO1234  
TRUE0 	 CALL CY2ZERO  
	 RET  
LOWER3 	 MVI L,0  
	 CPI 0  
	 JZ LOWER3END  
	 CPI 1  
	 JZ LOWER3END  
	 MVI L,1  
	 CPI 2  
	 JZ LOWER3END  
	 CALL NEWLINE  
	 LXI H,TEXT2HIGHER  
	 RST 3  
	 HLT  
LOWER3END 	 RET  
LOWER6 	 MVI L,0  
	 CPI 0  
	 JZ LOWER6END  
	 CPI 1  
	 JZ LOWER6END  
	 CPI 2  
	 JZ LOWER6END  
	 CPI 3  
	 JZ LOWER6END  
	 CPI 4  
	 JZ LOWER6END  
	 MVI L,1  
	 CPI 5  
	 JZ LOWER6END  
	 CALL NEWLINE  
	 LXI H,TEXT2HIGHER  
	 RST 3  
	 HLT  
LOWER6END 	 RET  
CHECKFLAG 	 MOV H,A  
	 MVI A,1  
	 CMP L  
	 MOV A,H  
	 RET  
CY2ZERO 	 JNC CY2ZEROEND  
	 CMC  
CY2ZEROEND 	 RET  
TEXT1 	 DB 'INSERT FIRST NUMBER [0-255]: @'              
TEXT2 	 DB 'INSERT SECOND NUMBER [0-255]: @'                                              
TEXTZERO 	 DB 'THE RESULT OF MULTIPLICATION BY "0" IS 0@'                                         
TEXTRESULT 	 DB 'MULTIPLICATION RESULT: @'                                
TEXTNOTANUMBER 	 DB 'NOT A NUMBER!@'                          
TEXT2HIGHER 	 DB 'TOO LARGE NUMBER!@'  
